### ISSUE TITLE
Make GS Result Rendering faster

### ISSUE THREAD

**Issue by Katkat954** [SPSquonK/useleSS#49]
@SPSquonK 

https://github.com/SPSquonK/useleSS/blob/7429607e9b8db28bd1c4af069a67743ff5a9d021/Source/Neuz/DPClient.cpp#L6119-L6363

Code has multiple issues making the rendering of the GS result slow.

**Comment by SPSquonK** [comment]
(Thanks for the report)

Closed by PR #53

The issue was solved especially in this commit : https://github.com/SPSquonK/useleSS/pull/53/commits/16d5d2d928302b220189d981c771fad61f417b91

GS result was slow mainly because the InsertLog is called several times and this function costs a lot.

9 * 9 * 50 `__GCGETPOINT ` to process:
- With this commit: about 350 ms
- Without this commit: At least 1 minute
